name: Push Updated Code

on: 
  push: 
      branches:
              - 'master'
        
jobs:

  build:
    name: build
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:

    - uses: actions/checkout@v2
      name: Checkout repository

    - run: npm run build
      name: Build Sahas App

    - run: Compress-Archive -Path builds/*.* -Destination sahas.zip
      name: Zipping App

    - name: 'Preparing Deployables'
      uses: actions/upload-artifact@v3
      with:
         name: sahas.zip
         path: sahas.zip
         retention-days: 1

  deploy:
        name: deploy
        needs: build
        permissions: write-all
        runs-on: ubuntu-latest
        steps:

            - name: Downloading Deployables
              uses: actions/download-artifact@v3
              with:
                  name: sahas.zip

            - name: Starting Deployments
              run: unzip sahas.zip -d deploymentFiles

            - name: Deploying
              run: echo "ftp -n <<EOF" > ftp.sh;
                   echo "open ftp.sahasinstitute.com" >> ftp.sh;
                   echo "user u496732460.LCJpaQ37NH3Wdij mFY52q71yVVBHfr" >> ftp.sh;
                   echo "quote pasv" >> ftp.sh;
                   echo "binary" >> ftp.sh;
                   echo "prompt off" >> ftp.sh;
                   echo "mput *" >> ftp.sh;
                   echo "EOF" >> ftp.sh;
                   chmod +x ftp.sh;
                   cd deploymentFiles;
                   ls;                   
                   ../ftp.sh;