name: Push Updated Code

on: 
  push: 
      branches:
              - 'master'
        
jobs:

  build:
    name: build
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Sahas App
      run: npm run build
      
    - run: Compress-Archive -Path builds/*.* -Destination sahas.zip
      name: Zipping App

    - name: 'Preparing Deployables'
      uses: actions/upload-artifact@v3
      with:
         name: sahas.zip
         path: sahas.zip
         retention-days: 1

  deploy:
        name: deploy
        needs: build
        permissions: write-all
        runs-on: ubuntu-latest
        steps:

            - name: Downloading Deployables
              uses: actions/download-artifact@v3
              with:
                  name: sahas.zip

            - name: Starting Deployments
              run: unzip sahas.zip -d deploymentFiles

            - name: Prepare Direct Download File
              run : cd deploymentFiles;file=$(ls *.exe); zip -r "$file.zip" "$file"

            - name: Deploy Updates
              run: echo "ftp -n <<EOF" > ftp.sh;
                   echo "open ftp.sahasinstitute.com" >> ftp.sh;
                   echo "user u496732460.C0mpl3xU3rnme R3nD0mK3yW0rd" >> ftp.sh;
                   echo "quote pasv" >> ftp.sh;
                   echo "binary" >> ftp.sh;
                   echo "prompt off" >> ftp.sh;
                   echo "mput *.zip" >> ftp.sh;
                   echo "cd assets/win_updates" >> ftp.sh;
                   echo "mdelete *" >> ftp.sh;
                   echo "mput latest.yml" >> ftp.sh;
                   echo "mput *.exe*" >> ftp.sh;
                   echo "EOF" >> ftp.sh;
                   chmod +x ftp.sh;
                   ls;                   
                   ../ftp.sh;